services:
  - type: web
    name: dinner-bonanza
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: dinner-bonanza-db
          property: connectionString

databases:
  - name: dinner-bonanza-db
    databaseName: dinner_bonanza
    user: dinner_bonanza
    plan: free 